#!zsh
# auto-fu-widgets: ZLE widget wrappers and keymap delegation functions

# Shared list of wrapped editing widgets (used by auto-fu core too)
typeset -ga _afu_wrapped_widgets
_afu_wrapped_widgets=(self-insert backward-delete-char backward-kill-word
                      kill-line kill-whole-line kill-word magic-space yank)

# --- Generate afu+ widget wrappers (delegate to with-afu~) ---

for _afu_w in $_afu_wrapped_widgets; do
	eval "afu+$_afu_w () { with-afu~ .$_afu_w $_afu_wrapped_widgets }"
done

# --- Accept-line widgets ---

afu+accept-line () {
	__accepted=($WIDGET ${=NUMERIC:+-n $NUMERIC} "$@")
	zle .accept-line
	zstyle -T ':auto-fu:var' postdisplay/clearp && POSTDISPLAY=""
	return 0
}
afu+accept-and-hold () {
	__accepted=($WIDGET ${=NUMERIC:+-n $NUMERIC} "$@")
	zle .accept-and-hold
	zstyle -T ':auto-fu:var' postdisplay/clearp && POSTDISPLAY=""
	return 0
}
afu+accept-line-and-down-history () {
	__accepted=($WIDGET ${=NUMERIC:+-n $NUMERIC} "$@")
	zle .accept-line-and-down-history
	zstyle -T ':auto-fu:var' postdisplay/clearp && POSTDISPLAY=""
	return 0
}

# --- Vi mode widgets ---

afu+vi-cmd-mode () {
	((afu_in_p==1)) && BUFFER="$buffer_cur"
	zle -K afu-vicmd
}
afu+vi-ins-mode () {
	zle -K afu
}
afu+vi-visual-exit () {
	zle vi-visual-exit
	zle -K afu
	zle -K afu-vicmd
}
afu+vi-visual-kill-and-insert () {
	zle vi-visual-kill-and-vicmd
	zle -K afu
}
afu+vi-visual-kill-and-vicmd () {
	zle vi-visual-kill-and-vicmd
	zle -K afu
	zle -K afu-vicmd
}

# --- EOF widgets ---

afu+orf-ignoreeof-deletechar-list () {
	afu-eof-maybe afu-ignore-eof zle delete-char-or-list
}
afu+orf-exit-deletechar-list () {
	afu-eof-maybe exit zle delete-char-or-list
}

# --- Cursor movement ---

afu-cursor-right () {
	(( CURSOR += 1 ))
}
afu-cursor-left () {
	(( CURSOR -= 1 ))
}

# --- Generate keymap delegation wrappers ---

for _afu_w in $_afu_wrapped_widgets; do
	eval "$_afu_w-by-keymap () {
		if (( \$+widgets[\$KEYMAP+$_afu_w] == 1 )); then
			zle \$KEYMAP+$_afu_w \"\$@\"
		else
			zle .$_afu_w \"\$@\"
		fi
	}"
done
unset _afu_w
